---
- name: Run a script locally
  hosts: all
 
  tasks:
 
  - name: run a script locally
    script: /tmp/audit_linux.sh
  
  - name: get generated xml file
    shell: ls -t `hostname`*.xml | head -1
    register: output_xml
    
  - debug:
      var: output_xml
      
  - name: fetch to awx server
    fetch:
      src: "{{ output_xml.stdout }}"
      dest: /tmp/fetched
 
